<?php

namespace MaterialsBundle\Repository;

/**
 * BankAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BankAccountRepository extends \Doctrine\ORM\EntityRepository
{
}
