<?php

namespace MaterialsBundle\Repository;

/**
 * InsuranceCompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InsuranceCompanyRepository extends \Doctrine\ORM\EntityRepository
{
}
