<?php

namespace MaterialsBundle\Repository;

/**
 * KioskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KioskRepository extends \Doctrine\ORM\EntityRepository
{
}
