<?php

namespace MaterialsBundle\Repository;

/**
 * LeasingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeasingRepository extends \Doctrine\ORM\EntityRepository
{
}
