<?php

namespace MaterialsBundle\Repository;

/**
 * MechanicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MechanicRepository extends \Doctrine\ORM\EntityRepository
{
}
