employmentcontract_index:
    path:     /
    defaults: { _controller: "StaffBundle:EmploymentContract:index" }
    methods:  GET

employmentcontract_show:
    path:     /{id}/show
    defaults: { _controller: "StaffBundle:EmploymentContract:show" }
    methods:  GET

employmentcontract_new:
    path:     /new
    defaults: { _controller: "StaffBundle:EmploymentContract:new" }
    methods:  [GET, POST]

employmentcontract_edit:
    path:     /{id}/edit
    defaults: { _controller: "StaffBundle:EmploymentContract:edit" }
    methods:  [GET, POST]

employmentcontract_delete:
    path:     /{id}/delete
    defaults: { _controller: "StaffBundle:EmploymentContract:delete" }
    methods:  DELETE
