employmentfunction_index:
    path:     /
    defaults: { _controller: "StaffBundle:EmploymentFunction:index" }
    methods:  GET

employmentfunction_show:
    path:     /{id}/show
    defaults: { _controller: "StaffBundle:EmploymentFunction:show" }
    methods:  GET

employmentfunction_new:
    path:     /new
    defaults: { _controller: "StaffBundle:EmploymentFunction:new" }
    methods:  [GET, POST]

employmentfunction_edit:
    path:     /{id}/edit
    defaults: { _controller: "StaffBundle:EmploymentFunction:edit" }
    methods:  [GET, POST]

employmentfunction_delete:
    path:     /{id}/delete
    defaults: { _controller: "StaffBundle:EmploymentFunction:delete" }
    methods:  DELETE
