workplace_index:
    path:     /
    defaults: { _controller: "StaffBundle:Workplace:index" }
    methods:  GET

workplace_show:
    path:     /{id}/show
    defaults: { _controller: "StaffBundle:Workplace:show" }
    methods:  GET

workplace_new:
    path:     /new
    defaults: { _controller: "StaffBundle:Workplace:new" }
    methods:  [GET, POST]

workplace_edit:
    path:     /{id}/edit
    defaults: { _controller: "StaffBundle:Workplace:edit" }
    methods:  [GET, POST]

workplace_delete:
    path:     /{id}/delete
    defaults: { _controller: "StaffBundle:Workplace:delete" }
    methods:  DELETE
