brand_index:
    path:     /
    defaults: { _controller: "MaterialsBundle:Brand:index" }
    methods:  GET

brand_show:
    path:     /{id}/show
    defaults: { _controller: "MaterialsBundle:Brand:show" }
    methods:  GET

brand_new:
    path:     /new
    defaults: { _controller: "MaterialsBundle:Brand:new" }
    methods:  [GET, POST]

brand_edit:
    path:     /{id}/edit
    defaults: { _controller: "MaterialsBundle:Brand:edit" }
    methods:  [GET, POST]

brand_delete:
    path:     /{id}/delete
    defaults: { _controller: "MaterialsBundle:Brand:delete" }
    methods:  DELETE
