leasing_index:
    path:     /
    defaults: { _controller: "MaterialsBundle:Leasing:index" }
    methods:  GET

leasing_show:
    path:     /{id}/show
    defaults: { _controller: "MaterialsBundle:Leasing:show" }
    methods:  GET

leasing_new:
    path:     /new
    defaults: { _controller: "MaterialsBundle:Leasing:new" }
    methods:  [GET, POST]

leasing_edit:
    path:     /{id}/edit
    defaults: { _controller: "MaterialsBundle:Leasing:edit" }
    methods:  [GET, POST]

leasing_delete:
    path:     /{id}/delete
    defaults: { _controller: "MaterialsBundle:Leasing:delete" }
    methods:  DELETE
