subfamily_index:
    path:     /
    defaults: { _controller: "MaterialsBundle:SubFamily:index" }
    methods:  GET

subfamily_show:
    path:     /{id}/show
    defaults: { _controller: "MaterialsBundle:SubFamily:show" }
    methods:  GET

subfamily_new:
    path:     /new
    defaults: { _controller: "MaterialsBundle:SubFamily:new" }
    methods:  [GET, POST]

subfamily_edit:
    path:     /{id}/edit
    defaults: { _controller: "MaterialsBundle:SubFamily:edit" }
    methods:  [GET, POST]

subfamily_delete:
    path:     /{id}/delete
    defaults: { _controller: "MaterialsBundle:SubFamily:delete" }
    methods:  DELETE
