app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

staff:
    resource: "@StaffBundle/Resources/config/routing.yml"
    prefix:   /

project:
    resource: "@ProjectBundle/Resources/config/routing.yml"
    prefix:   /

materials:
    resource: "@MaterialsBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"