supplier_index:
    path:     /
    defaults: { _controller: "ProjectBundle:Supplier:index" }
    methods:  GET

supplier_show:
    path:     /{id}/show
    defaults: { _controller: "ProjectBundle:Supplier:show" }
    methods:  GET



