typeofconstructionmaterials_index:
    path:     /
    defaults: { _controller: "ProjectBundle:TypeOfConstructionMaterials:index" }
    methods:  GET

typeofconstructionmaterials_show:
    path:     /{id}/show
    defaults: { _controller: "ProjectBundle:TypeOfConstructionMaterials:show" }
    methods:  GET

typeofconstructionmaterials_new:
    path:     /new
    defaults: { _controller: "ProjectBundle:TypeOfConstructionMaterials:new" }
    methods:  [GET, POST]

typeofconstructionmaterials_edit:
    path:     /{id}/edit
    defaults: { _controller: "ProjectBundle:TypeOfConstructionMaterials:edit" }
    methods:  [GET, POST]

typeofconstructionmaterials_delete:
    path:     /{id}/delete
    defaults: { _controller: "ProjectBundle:TypeOfConstructionMaterials:delete" }
    methods:  DELETE
