producttype_index:
    path:     /
    defaults: { _controller: "PurchaseBundle:ProductType:index" }
    methods:  GET

producttype_show:
    path:     /{id}/show
    defaults: { _controller: "PurchaseBundle:ProductType:show" }
    methods:  GET

producttype_new:
    path:     /new
    defaults: { _controller: "PurchaseBundle:ProductType:new" }
    methods:  [GET, POST]

producttype_edit:
    path:     /{id}/edit
    defaults: { _controller: "PurchaseBundle:ProductType:edit" }
    methods:  [GET, POST]

producttype_delete:
    path:     /{id}/delete
    defaults: { _controller: "PurchaseBundle:ProductType:delete" }
    methods:  DELETE
