product_index:
    path:     /
    defaults: { _controller: "PurchaseBundle:Product:index" }
    methods:  GET

product_list_project:
    path:     /project/{id}
    defaults: { _controller: "PurchaseBundle:Product:listByProject" }
    methods:  GET

product_show:
    path:     /{id}/show
    defaults: { _controller: "PurchaseBundle:Product:show" }
    methods:  GET

product_new:
    path:     /new
    defaults: { _controller: "PurchaseBundle:Product:new" }
    methods:  [GET, POST]

product_edit:
    path:     /{id}/edit
    defaults: { _controller: "PurchaseBundle:Product:edit" }
    methods:  [GET, POST]

product_delete:
    path:     /{id}/delete
    defaults: { _controller: "PurchaseBundle:Product:delete" }
    methods:  DELETE
