<?php

namespace PurchaseBundle\Repository;

/**
 * PartnerCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartnerCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
