<?php

namespace ProjectBundle\Repository;

/**
 * CautionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CautionRepository extends \Doctrine\ORM\EntityRepository
{
}
