<?php

namespace ProjectBundle\Repository;

/**
 * JourneyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JourneyRepository extends \Doctrine\ORM\EntityRepository
{
}
