<?php

namespace ProjectBundle\Repository;

/**
 * MaterialsOfConstructionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaterialsOfConstructionRepository extends \Doctrine\ORM\EntityRepository
{
}
