<?php

namespace ProjectBundle\Repository;

/**
 * TypeOfConstructionMaterialsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeOfConstructionMaterialsRepository extends \Doctrine\ORM\EntityRepository
{
}
