materials_brand:
    resource: "@MaterialsBundle/Resources/config/routing/brand.yml"
    prefix:   /brand
    
materials_model:
    resource: "@MaterialsBundle/Resources/config/routing/model.yml"
    prefix:   /model 
    
materials_equipment:
    resource: "@MaterialsBundle/Resources/config/routing/equipment.yml"
    prefix:   /equipment 
    
materials_subfamily:
    resource: "@MaterialsBundle/Resources/config/routing/subfamily.yml"
    prefix:   /subfamily
     
materials_family:
    resource: "@MaterialsBundle/Resources/config/routing/family.yml"
    prefix:   /family

materials_kiosk:
    resource: "@MaterialsBundle/Resources/config/routing/kiosk.yml"
    prefix:   /kiosk

materials_mechanic:
    resource: "@MaterialsBundle/Resources/config/routing/mechanic.yml"
    prefix:   /mechanic

materials_insurancecompany:
    resource: "@MaterialsBundle/Resources/config/routing/insurancecompany.yml"
    prefix:   /insurancecompany

materials_store:
    resource: "@MaterialsBundle/Resources/config/routing/store.yml"
    prefix:   /store

materials_bank:
    resource: "@MaterialsBundle/Resources/config/routing/bank.yml"
    prefix:   /bank

materials_leasing:
    resource: "@MaterialsBundle/Resources/config/routing/leasing.yml"
    prefix:   /leasing
