project_client:
    resource: "@ProjectBundle/Resources/config/routing/client.yml"
    prefix:   /client

project_project:
    resource: "@ProjectBundle/Resources/config/routing/project.yml"
    prefix:   /project

