<?php

namespace StaffBundle\Repository;

use StaffBundle\Entity\Clocking;

/**
 * ClockingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClockingRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByCriteria($criteria)
    {
        $qb = $this->createQueryBuilder('cl');
        $qb
            ->select('cl.date')
            ->orderBy('cl.date', 'DESC')
            ->groupBy('cl.date');

        return $qb->getQuery()->getResult();
    }
}
