<?php

namespace StaffBundle\Repository;

/**
 * ClockingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClockingRepository extends \Doctrine\ORM\EntityRepository
{
}
