<?php

namespace StaffBundle\Repository;

use StaffBundle\Entity\Clocking;

/**
 * ClockingReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClockingReportRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByCriteria()
    {
        $qb = $this->createQueryBuilder('cl');
        $qb
            ->select('cl.date, cl.id')
            ->orderBy('cl.date', 'DESC')
            ->groupBy('cl.date');

        return $qb->getQuery()->getResult();
    }

    public function getCostByProject($project)
    {
        $qb = $this->createQueryBuilder('cl');
        $qb
            ->select('count(cl.id) as totalWorkedDays, SUM(p.dailyRate) as totalCost')
            ->leftJoin('cl.personal', 'p')
            ->where('cl.constructionSite = :project')
            ->setParameter('project', $project);

        return $qb->getQuery()->getSingleResult();
    }
}
