<?php

namespace StaffBundle\Repository;

/**
 * EmploymentContractRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmploymentContractRepository extends \Doctrine\ORM\EntityRepository
{
}
