<?php

namespace StaffBundle\Repository;

/**
 * LeaveApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeaveApplicationRepository extends \Doctrine\ORM\EntityRepository
{
}
