<?php

namespace StaffBundle\Repository;

/**
 * MonthlyPaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MonthlyPaymentRepository extends \Doctrine\ORM\EntityRepository
{
}
