<?php

namespace StaffBundle\Repository;
use StaffBundle\Entity\EmploymentFunction;
use StaffBundle\Entity\Personal;

/**
 * PersonalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonalRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function countByFunction()
    {
        $qb = $this->createQueryBuilder('p');
        $qb
            ->select('f.name, count(p.id) as total')
            ->leftJoin('p.function', 'f')
            ->groupBy('f.name')
            ;

        return $qb->getQuery()->getResult();
    }
}
