<?php

namespace StaffBundle\Repository;

/**
 * WorkplaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkplaceRepository extends \Doctrine\ORM\EntityRepository
{
}
